id: PE6545A8A
initial_creation_type: input
source_metadata:
  Title: Mah훮megha S큰tra
  Editor: Moriguchi Mitsutoshi
  Publisher: Annual of the Institute for Comprehensive Studies of Buddhism, Taisho
    University
  Place of Publication: Japan
  Year: '1980'
  Mah훮 megha s큰tram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:04:58.017744'
last_modified_at: '2022-03-08T16:04:58.017753'
